version: '3'
services:
  webapp:
    build:
      context: .  # Utilize the current directory as the build context
      dockerfile: Dockerfile  # Specify the Dockerfile to use
    ports:
      - "8080:8080"  # Map port 8080 of the host to port 8080 of the container
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql  # Use the service name of the MySQL container
      - MYSQL_PORT=3306
      - MYSQL_DATABASE="employee_management"
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "employee_management" 
