version: '3'
services:
  time-management-webapp-1:
    image: time-management-webapp
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=time-management-mysql-1  # Use the name of the MySQL service
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=employee_management
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
  
  time-management-mysql-1:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: employee_management
    ports:
      - "3306:3306"
      - ./employee_management.sql:/docker-entrypoint-initdb.d/employee_management.sql
